name: Build and Deploy Code

on: 
  push:
    branches: ["main"]

jobs:
  build:
    environment:
      name: CI/CD
    env:
      DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PWD: ${{ secrets.DB_PWD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}_test
          POSTGRES_PASSWORD: ${{ secrets.DB_PWD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v6
      - name: Install python version 
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Update pip
        run: python -m pip install --upgrade pip 
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Testing with pytest
        run: |
          pip install pytest
          pytest 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sulavk/fastapi_practice:latest
  deploy:
    environment:
      name: CI/CD
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploying to Render
        uses: actions/checkout@main 
      - name: Create deployment
        uses: sws2apps/render-deployment@main 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          node-version: lts/Jod 
          cli-version: 2.2.0 
